# Generated by Django 3.0.3 on 2020-03-02 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_lab', models.CharField(max_length=120, verbose_name='Port')),
                ('baudrate', models.DecimalField(decimal_places=0, max_digits=6)),
                ('timeout', models.DecimalField(decimal_places=0, max_digits=4)),
                ('time_of_connection', models.DateTimeField(auto_now_add=True)),
                ('chattext', models.TextField(blank=True)),
                ('username', models.CharField(blank=True, max_length=120)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
