# Generated by Django 2.1.15 on 2020-01-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oc_lab', models.CharField(max_length=120)),
                ('baudrate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('timeout', models.DecimalField(decimal_places=1, max_digits=4)),
                ('time_of_connection', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
