# Generated by Django 2.1.15 on 2020-01-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_db',
            name='baudrate',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='connection_db',
            name='timeout',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
