# Generated by Django 3.0.3 on 2020-03-02 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20200302_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection_db',
            name='username',
        ),
    ]
