# Generated by Django 2.1.15 on 2020-01-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20200124_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_db',
            name='baudrate',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
