# Generated by Django 3.0.4 on 2020-03-20 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
        ('connection', '0002_connection_db_monitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_db',
            name='monitor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Monitor_Db'),
        ),
    ]
