# Generated by Django 2.1.15 on 2020-01-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_auto_20200124_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection_db',
            name='chattext',
            field=models.TextField(default=123),
            preserve_default=False,
        ),
    ]
