# Generated by Django 2.1.15 on 2020-01-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_connection_db_chattext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection_db',
            name='chattext',
            field=models.TextField(blank=True),
        ),
    ]
