# Generated by Django 3.0.4 on 2020-03-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_auto_20200320_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection_db',
            name='chattext',
        ),
    ]
