# Generated by Django 2.1.15 on 2020-01-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0006_connection_db_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection_db',
            name='connected',
        ),
    ]
