# Generated by Django 2.1.15 on 2020-02-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0007_remove_connection_db_connected'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection_db',
            name='username',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
