version: "2.1"

services:
  redis:
    restart: always
    container_name: OC_redis_cont
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'

  app:
    restart: always
    build: .
    labels:
      io.balena.features.supervisor-api: '1'
    image: oc-image:octag
    depends_on:
      - redis
    environment:
      - UDEV=1
    ports:
      - "8000:8000" # Map 8000 to 8000 of our docker image
    privileged: true
    cap_add:
      - SYS_ADMIN
    devices:
      - '/dev:/dev'
    command: >
      sh -c " python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
