FROM base

COPY requirements/amd64.txt /requirements.txt

# Installing Rust for compiling cryptography in ARMv7
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN apt install build-essential libssl-dev libffi-dev rustc -y

RUN pip install -r /requirements.txt
RUN mkdir /app
WORKDIR /app
# Copy the app folder from system to docker
COPY ./app /app




