FROM ocmanager/ocmanager:base

COPY requirements/armv7.txt /requirements.txt

RUN pip install --upgrade pip

RUN cat /requirements.txt | xargs pip install
RUN mkdir /app
WORKDIR /app
# Copy the app folder from system to docker
COPY ./app /app

RUN export PYTHONPATH='/usr/lib/python3/dist-packages'
ENV PYTHONPATH='/usr/lib/python3/dist-packages'

# -D is only to run the apps without root premision
# RUN adduser user
# RUN adduser -D user
# USER user
