# Generated by Django 3.0.5 on 2020-07-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraControls_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_exposure', models.CharField(blank=True, choices=[('0', 'off'), ('1', 'auto')], max_length=255, null=True)),
                ('exposure_dynamic_framerate', models.BooleanField(blank=True, null=True)),
                ('auto_exposure_bias', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('exposure_time_absolute', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('white_balance_auto_preset', models.CharField(blank=True, choices=[('0', 'off'), ('1', 'auto'), ('2', 'sunlight'), ('3', 'cloudy'), ('4', 'shade'), ('5', 'tungsten'), ('6', 'fluorescent'), ('7', 'incandescent'), ('8', 'flash'), ('9', 'horizon')], max_length=255, null=True)),
                ('image_stabilization', models.BooleanField(blank=True, null=True)),
                ('iso_sensitivity', models.CharField(blank=True, choices=[('0', 0), ('1', 100000), ('2', 200000), ('3', 400000), ('4', 900000)], max_length=255, null=True)),
                ('iso_sensitivity_auto', models.CharField(blank=True, choices=[('0', 'Manual'), ('1', 'Auto')], max_length=255, null=True)),
                ('exposure_metering_mode', models.CharField(blank=True, choices=[('0', 'Averange'), ('1', 'Center Weighted'), ('2', 'Spot')], max_length=255, null=True)),
                ('scene_mode', models.CharField(blank=True, choices=[('0', 'None'), ('8', 'Night'), ('11', 'Sports')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatePhoto_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='UserControls_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('contrast', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('saturation', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('red_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('blue_balance', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('horizontal_flip', models.BooleanField(blank=True, null=True)),
                ('vertical_flip', models.BooleanField(blank=True, null=True)),
                ('power_line_frequency', models.CharField(blank=True, choices=[('0', 'Disable'), ('1', '50 Hz'), ('2', '60 Hz'), ('3', 'Auto')], max_length=255, null=True)),
                ('sharpness', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('color_effects', models.CharField(blank=True, choices=[('13', 'Solarization'), ('9', 'Vivid'), ('12', 'Silhouette'), ('5', 'Sketch'), ('3', 'Negative'), ('2', 'Sepia'), ('6', 'Sky Blue'), ('10', 'Aqua'), ('4', 'Emboss'), ('11', 'Art Freeze'), ('1', 'Black & White'), ('8', 'Skin Whiten'), ('14', 'Set Cb/Cr'), ('0', 'None'), ('7', 'Grass Green')], max_length=255, null=True)),
                ('rotate', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('color_effects_cbcr', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
