# Generated by Django 3.0.5 on 2020-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('5', 'Sketch'), ('7', 'Grass Green'), ('14', 'Set Cb/Cr'), ('4', 'Emboss'), ('3', 'Negative'), ('1', 'Black & White'), ('10', 'Aqua'), ('8', 'Skin Whiten'), ('2', 'Sepia'), ('12', 'Silhouette'), ('11', 'Art Freeze'), ('0', 'None'), ('9', 'Vivid'), ('6', 'Sky Blue'), ('13', 'Solarization')], max_length=255, null=True),
        ),
    ]
