# Generated by Django 3.0.5 on 2020-07-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_auto_20200706_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('11', 'Art Freeze'), ('1', 'Black & White'), ('4', 'Emboss'), ('5', 'Sketch'), ('6', 'Sky Blue'), ('0', 'None'), ('3', 'Negative'), ('13', 'Solarization'), ('8', 'Skin Whiten'), ('12', 'Silhouette'), ('10', 'Aqua'), ('14', 'Set Cb/Cr'), ('7', 'Grass Green'), ('9', 'Vivid'), ('2', 'Sepia')], max_length=255, null=True),
        ),
    ]
