# Generated by Django 3.0.5 on 2020-07-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_auto_20200706_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('1', 'Black & White'), ('2', 'Sepia'), ('3', 'Negative'), ('4', 'Emboss'), ('5', 'Sketch'), ('6', 'Sky Blue'), ('7', 'Grass Green'), ('8', 'Skin Whiten'), ('9', 'Vivid'), ('10', 'Aqua'), ('11', 'Art Freeze'), ('12', 'Silhouette'), ('13', 'Solarization'), ('14', 'Set Cb/Cr')], max_length=255, null=True),
        ),
    ]
