# Generated by Django 3.0.5 on 2020-06-24 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0003_usercontrols_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[(10, 'Aqua'), (5, 'Sketch'), (11, 'Art Freeze'), (14, 'Set Cb/Cr'), (9, 'Vivid'), (3, 'Negative'), (0, 'None'), (7, 'Grass Green'), (1, 'Black & White'), (6, 'Sky Blue'), (2, 'Sepia'), (13, 'Solarization'), (8, 'Skin Whiten'), (4, 'Emboss'), (12, 'Silhouette')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Images_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('gcode_url', models.CharField(max_length=100, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
