# Generated by Django 3.0.8 on 2020-07-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20200706_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='images_db',
            name='path',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
