# Generated by Django 3.0.5 on 2020-06-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_auto_20200624_1155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images_db',
            old_name='gcode_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[(12, 'Silhouette'), (11, 'Art Freeze'), (1, 'Black & White'), (13, 'Solarization'), (7, 'Grass Green'), (4, 'Emboss'), (9, 'Vivid'), (3, 'Negative'), (10, 'Aqua'), (14, 'Set Cb/Cr'), (2, 'Sepia'), (8, 'Skin Whiten'), (0, 'None'), (6, 'Sky Blue'), (5, 'Sketch')], max_length=255, null=True),
        ),
    ]
