# Generated by Django 3.0.9 on 2020-08-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_images_db_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leds_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uv365_power', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('uv278_power', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('rgb_power', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
        ),
    ]
