# Generated by Django 3.0.5 on 2020-06-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_auto_20200624_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images_db',
            name='image',
        ),
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[(12, 'Silhouette'), (11, 'Art Freeze'), (7, 'Grass Green'), (4, 'Emboss'), (2, 'Sepia'), (8, 'Skin Whiten'), (9, 'Vivid'), (0, 'None'), (6, 'Sky Blue'), (13, 'Solarization'), (1, 'Black & White'), (14, 'Set Cb/Cr'), (3, 'Negative'), (5, 'Sketch'), (10, 'Aqua')], max_length=255, null=True),
        ),
    ]
