# Generated by Django 3.0.9 on 2020-08-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_leds_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leds_db',
            name='rgb_power',
        ),
    ]
