# Generated by Django 3.0.5 on 2020-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0006_auto_20200624_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[(3, 'Negative'), (2, 'Sepia'), (7, 'Grass Green'), (6, 'Sky Blue'), (13, 'Solarization'), (10, 'Aqua'), (12, 'Silhouette'), (4, 'Emboss'), (0, 'None'), (8, 'Skin Whiten'), (9, 'Vivid'), (1, 'Black & White'), (5, 'Sketch'), (11, 'Art Freeze'), (14, 'Set Cb/Cr')], max_length=255, null=True),
        ),
    ]
