# Generated by Django 3.1.1 on 2020-09-08 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0007_remove_leds_db_rgb_power'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images_db',
            name='path',
        ),
        migrations.RemoveField(
            model_name='images_db',
            name='url',
        ),
        migrations.AddField(
            model_name='images_db',
            name='photo',
            field=models.ImageField(default='/default.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='images_db',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Detection_ZeroPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('zero_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
