# Generated by Django 3.0.5 on 2020-06-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0007_auto_20200625_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameracontrols_db',
            name='exposure_metering_mode',
            field=models.CharField(blank=True, choices=[('0', 'Averange'), ('1', 'Center Weighted'), ('2', 'Spot')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cameracontrols_db',
            name='iso_sensitivity',
            field=models.CharField(blank=True, choices=[('0', 0), ('1', 100000), ('2', 200000), ('3', 400000), ('4', 900000)], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cameracontrols_db',
            name='iso_sensitivity_auto',
            field=models.CharField(blank=True, choices=[('0', 'Manual'), ('1', 'Auto')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cameracontrols_db',
            name='scene_mode',
            field=models.CharField(blank=True, choices=[('0', 'None'), ('8', 'Night'), ('11', 'Sports')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('5', 'Sketch'), ('8', 'Skin Whiten'), ('1', 'Black & White'), ('12', 'Silhouette'), ('2', 'Sepia'), ('4', 'Emboss'), ('14', 'Set Cb/Cr'), ('0', 'None'), ('10', 'Aqua'), ('7', 'Grass Green'), ('6', 'Sky Blue'), ('11', 'Art Freeze'), ('9', 'Vivid'), ('13', 'Solarization'), ('3', 'Negative')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usercontrols_db',
            name='power_line_frequency',
            field=models.CharField(blank=True, choices=[('0', 'Disable'), ('1', '50 Hz'), ('2', '60 Hz'), ('3', 'Auto')], max_length=255, null=True),
        ),
    ]
