# Generated by Django 3.0.5 on 2020-06-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0008_auto_20200625_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('9', 'Vivid'), ('6', 'Sky Blue'), ('12', 'Silhouette'), ('14', 'Set Cb/Cr'), ('5', 'Sketch'), ('4', 'Emboss'), ('10', 'Aqua'), ('11', 'Art Freeze'), ('3', 'Negative'), ('0', 'None'), ('7', 'Grass Green'), ('1', 'Black & White'), ('8', 'Skin Whiten'), ('2', 'Sepia'), ('13', 'Solarization')], max_length=255, null=True),
        ),
    ]
