# Generated by Django 3.0.5 on 2020-06-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0009_auto_20200625_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('11', 'Art Freeze'), ('5', 'Sketch'), ('10', 'Aqua'), ('12', 'Silhouette'), ('4', 'Emboss'), ('6', 'Sky Blue'), ('3', 'Negative'), ('1', 'Black & White'), ('2', 'Sepia'), ('14', 'Set Cb/Cr'), ('0', 'None'), ('8', 'Skin Whiten'), ('9', 'Vivid'), ('7', 'Grass Green'), ('13', 'Solarization')], max_length=255, null=True),
        ),
    ]
