# Generated by Django 3.0.5 on 2020-07-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0010_auto_20200626_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('7', 'Grass Green'), ('6', 'Sky Blue'), ('12', 'Silhouette'), ('14', 'Set Cb/Cr'), ('2', 'Sepia'), ('10', 'Aqua'), ('5', 'Sketch'), ('0', 'None'), ('8', 'Skin Whiten'), ('4', 'Emboss'), ('3', 'Negative'), ('11', 'Art Freeze'), ('1', 'Black & White'), ('9', 'Vivid'), ('13', 'Solarization')], max_length=255, null=True),
        ),
    ]
