# Generated by Django 3.0.5 on 2020-07-01 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0011_auto_20200701_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('3', 'Negative'), ('8', 'Skin Whiten'), ('6', 'Sky Blue'), ('9', 'Vivid'), ('5', 'Sketch'), ('10', 'Aqua'), ('12', 'Silhouette'), ('13', 'Solarization'), ('2', 'Sepia'), ('7', 'Grass Green'), ('14', 'Set Cb/Cr'), ('11', 'Art Freeze'), ('0', 'None'), ('4', 'Emboss'), ('1', 'Black & White')], max_length=255, null=True),
        ),
    ]
