# Generated by Django 3.0.5 on 2020-07-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_auto_20200701_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('1', 'Black & White'), ('9', 'Vivid'), ('12', 'Silhouette'), ('14', 'Set Cb/Cr'), ('7', 'Grass Green'), ('10', 'Aqua'), ('6', 'Sky Blue'), ('2', 'Sepia'), ('8', 'Skin Whiten'), ('3', 'Negative'), ('13', 'Solarization'), ('11', 'Art Freeze'), ('4', 'Emboss'), ('5', 'Sketch'), ('0', 'None')], max_length=255, null=True),
        ),
    ]
