# Generated by Django 3.0.5 on 2020-07-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_auto_20200701_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontrols_db',
            name='color_effects',
            field=models.CharField(blank=True, choices=[('3', 'Negative'), ('0', 'None'), ('4', 'Emboss'), ('11', 'Art Freeze'), ('10', 'Aqua'), ('9', 'Vivid'), ('14', 'Set Cb/Cr'), ('1', 'Black & White'), ('2', 'Sepia'), ('8', 'Skin Whiten'), ('12', 'Silhouette'), ('5', 'Sketch'), ('7', 'Grass Green'), ('6', 'Sky Blue'), ('13', 'Solarization')], max_length=255, null=True),
        ),
    ]
