# Generated by Django 3.0.5 on 2020-05-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plateproperties_db',
            old_name='offsetx',
            new_name='offset_x',
        ),
        migrations.RenameField(
            model_name='plateproperties_db',
            old_name='offsety',
            new_name='offset_y',
        ),
        migrations.RenameField(
            model_name='plateproperties_db',
            old_name='sizex',
            new_name='size_x',
        ),
        migrations.RenameField(
            model_name='plateproperties_db',
            old_name='sizey',
            new_name='size_y',
        ),
    ]
