# Generated by Django 3.0.5 on 2020-05-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sampleapp', '0002_auto_20200511_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bandsettings_db',
            old_name='lengthbands',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='bandsettings_db',
            old_name='nbands',
            new_name='n_bands',
        ),
        migrations.RenameField(
            model_name='sampleapplication_db',
            old_name='deltapressure',
            new_name='delta_pressure',
        ),
        migrations.RenameField(
            model_name='sampleapplication_db',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='sampleapplication_db',
            old_name='motorspeed',
            new_name='motor_speed',
        ),
        migrations.RemoveField(
            model_name='bandsettings_db',
            name='bandsetting',
        ),
        migrations.AddField(
            model_name='bandsettings_db',
            name='main_property',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sampleapplication_db',
            name='auth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
