# Generated by Django 3.0.5 on 2020-05-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_auto_20200511_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandsettings_db',
            name='n_bands',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
