# Generated by Django 3.0.5 on 2020-05-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_auto_20200512_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandsettings_db',
            name='gap',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bandsettings_db',
            name='height',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bandsettings_db',
            name='length',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bandsettings_db',
            name='main_property',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sampleapplication_db',
            name='delta_pressure',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sampleapplication_db',
            name='motor_speed',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='sampleapplication_db',
            name='pressure',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
