# Generated by Django 3.0.5 on 2020-05-12 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0006_auto_20200512_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementSettings_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor_speed', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('delta_x', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('delta_y', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressureSettings_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressure', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('delta_pressure', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='sampleapplication_db',
            old_name='bandsettings',
            new_name='band_settings',
        ),
        migrations.RenameField(
            model_name='sampleapplication_db',
            old_name='plateproperties',
            new_name='plate_properties',
        ),
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='delta_pressure',
        ),
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='delta_x',
        ),
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='delta_y',
        ),
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='motor_speed',
        ),
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='pressure',
        ),
        migrations.AddField(
            model_name='sampleapplication_db',
            name='movement_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.MovementSettings_Db'),
        ),
        migrations.AddField(
            model_name='sampleapplication_db',
            name='pressure_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.PressureSettings_Db'),
        ),
    ]
