# Generated by Django 3.0.5 on 2020-05-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_auto_20200512_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandsettings_db',
            name='length',
        ),
        migrations.RemoveField(
            model_name='bandsettings_db',
            name='n_bands',
        ),
        migrations.AddField(
            model_name='bandsettings_db',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
