# Generated by Django 3.0.5 on 2020-05-29 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0008_auto_20200512_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pressuresettings_db',
            old_name='delta_pressure',
            new_name='frequency',
        ),
    ]
