# Generated by Django 3.0.5 on 2020-06-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0009_auto_20200529_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plateproperties_db',
            name='offset_x',
        ),
        migrations.RemoveField(
            model_name='plateproperties_db',
            name='offset_y',
        ),
        migrations.AddField(
            model_name='plateproperties_db',
            name='offset_bottom',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plateproperties_db',
            name='offset_left',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plateproperties_db',
            name='offset_rigth',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='plateproperties_db',
            name='offset_top',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
