# Generated by Django 3.0.5 on 2020-06-02 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0010_auto_20200602_0721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plateproperties_db',
            old_name='offset_rigth',
            new_name='offset_right',
        ),
    ]
