# Generated by Django 3.0.5 on 2020-06-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0011_auto_20200602_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresettings_db',
            name='temperature',
            field=models.DecimalField(decimal_places=0, max_digits=6, null=True),
        ),
    ]
