# Generated by Django 3.0.5 on 2020-06-15 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0012_pressuresettings_db_temperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandsComponents_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_number', models.DecimalField(decimal_places=0, max_digits=3, null=True)),
                ('description', models.CharField(max_length=120, null=True)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=6, null=True)),
                ('type', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='sampleapplication_db',
            name='bands_components',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.BandsComponents_Db'),
        ),
    ]
