# Generated by Django 3.0.5 on 2020-06-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0013_auto_20200615_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='bands_components',
        ),
        migrations.AddField(
            model_name='bandscomponents_db',
            name='sample',
            field=models.ManyToManyField(to='sampleapp.SampleApplication_Db'),
        ),
        migrations.AlterField(
            model_name='bandscomponents_db',
            name='band_number',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='bandscomponents_db',
            name='description',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bandscomponents_db',
            name='type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='bandscomponents_db',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
