# Generated by Django 3.0.5 on 2020-06-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0014_auto_20200615_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bandscomponents_db',
            name='sample',
        ),
        migrations.AddField(
            model_name='sampleapplication_db',
            name='components_settings',
            field=models.ManyToManyField(to='sampleapp.BandsComponents_Db'),
        ),
    ]
