# Generated by Django 3.0.5 on 2020-06-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0015_auto_20200615_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='components_settings',
        ),
        migrations.AddField(
            model_name='bandscomponents_db',
            name='sample_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.SampleApplication_Db'),
        ),
    ]
