# Generated by Django 3.0.5 on 2020-06-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0018_auto_20200616_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressuresettings_db',
            name='temperature_control',
        ),
        migrations.AlterField(
            model_name='pressuresettings_db',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
