# Generated by Django 3.0.8 on 2020-07-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0020_auto_20200617_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificFluid_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_number', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('density', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('viscosity', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
    ]
