# Generated by Django 3.0.8 on 2020-07-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0021_specificfluid_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specificfluid_db',
            old_name='band_number',
            new_name='band_numberS',
        ),
    ]
