# Generated by Django 3.0.8 on 2020-07-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0022_auto_20200724_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleapplication_db',
            name='specificfluid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.SpecificFluid_Db'),
        ),
    ]
