# Generated by Django 3.0.8 on 2020-07-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0023_sampleapplication_db_specificfluid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sampleapplication_db',
            name='specificfluid',
        ),
        migrations.AddField(
            model_name='bandscomponents_db',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bandscomponents_db',
            name='viscosity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.DeleteModel(
            name='SpecificFluid_Db',
        ),
    ]
