# Generated by Django 3.0.8 on 2020-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0024_auto_20200728_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressuresettings_db',
            name='nozzlediameter',
            field=models.CharField(default='0.05', max_length=120),
        ),
    ]
