# Generated by Django 3.1 on 2020-08-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0025_pressuresettings_db_nozzlediameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressuresettings_db',
            name='nozzlediameter',
            field=models.CharField(default='0.08', max_length=120),
        ),
    ]
