# Generated by Django 3.0.5 on 2020-05-28 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finecontrol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcodefile',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='gcodefile',
            name='filename',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gcodefile',
            name='gcode',
            field=models.FileField(null=True, upload_to='gcode/files'),
        ),
        migrations.AlterField(
            model_name='gcodefile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
