# Generated by Django 3.0.5 on 2020-05-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecontrol', '0002_auto_20200528_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcodefile',
            name='gcode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
