# Generated by Django 3.0.5 on 2020-05-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecontrol', '0003_auto_20200528_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcodefile',
            name='gcode',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
