# Generated by Django 3.0.5 on 2020-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecontrol', '0004_auto_20200528_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcodefile',
            name='gcode_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
