# Generated by Django 3.0.5 on 2020-06-26 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finecontrol', '0005_gcodefile_gcode_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningProcess_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_frequency', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('stop_frequency', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('steps', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
