# Generated by Django 3.1 on 2020-08-13 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finecontrol', '0007_zeroposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zeroposition',
            name='zero_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='zeroposition',
            name='zero_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
