# Generated by Django 3.0.3 on 2020-03-10 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BandSettings_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandsetting', models.CharField(max_length=120, null=True)),
                ('nbands', models.DecimalField(decimal_places=0, max_digits=6)),
                ('lengthbands', models.DecimalField(decimal_places=0, max_digits=6)),
                ('height', models.DecimalField(decimal_places=0, max_digits=6)),
                ('gap', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='PlateProperties_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizex', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('sizey', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('offsetx', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
                ('offsety', models.DecimalField(decimal_places=0, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SampleApplication_Db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motorspeed', models.DecimalField(decimal_places=0, max_digits=6)),
                ('pressure', models.DecimalField(decimal_places=0, max_digits=6)),
                ('deltapressure', models.DecimalField(decimal_places=0, max_digits=6)),
                ('auth_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bandsettings', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.BandSettings_Db')),
                ('plateproperties', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.PlateProperties_Db')),
            ],
        ),
    ]
