# Generated by Django 3.0.3 on 2020-03-10 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleapplication_db',
            name='bandsettings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.BandSettings_Db'),
        ),
    ]
