# Generated by Django 3.0.3 on 2020-03-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200310_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampleapplication_db',
            name='bandsettings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.BandSettings_Db'),
        ),
    ]
