# Generated by Django 3.0.3 on 2020-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200310_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sampleapplication_db',
            name='name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
