# Generated by Django 3.0.3 on 2020-03-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_sampleapplication_db_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleapplication_db',
            old_name='name',
            new_name='filename',
        ),
    ]
