# Generated by Django 3.0.8 on 2020-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsettings_dev_db',
            name='fluid',
            field=models.CharField(default='Methanol', max_length=120),
        ),
    ]
