# Generated by Django 3.0.8 on 2020-07-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_bandsettings_dev_db_fluid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandsettings_dev_db',
            name='density',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='bandsettings_dev_db',
            name='viscosity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
