# Generated by Django 3.0.8 on 2020-07-30 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0004_auto_20200729_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandsettings_dev_db',
            name='printBothways',
            field=models.CharField(default='Off', max_length=120),
        ),
    ]
