# Generated by Django 3.0.4 on 2020-03-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor_db',
            old_name='text',
            new_name='monitortext',
        ),
    ]
