name: Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the base image
        run: |
          docker buildx build \
            --tag ocmanager/ocmanager:latest \
            --platform linux/amd64,linux/arm64,linux/arm/v7 .
      - name: build the image for amd64
        run: |
          docker buildx build --push \
          --tag ocmanager/ocmanager:amd64 \
          --platform linux/amd64 .
          -f Dockerfile.amd64
      - name: build the image for arm/v7
        run: |
          docker buildx build --push \
            --tag ocmanager/ocmanager:armv7 \
            --platform linux/arm/v7 .
            -f Dockerfile.armv7